pipeline {
    agent {
        docker {
            image '03b4557ad7b9' 
            args '-v /root' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}